[package]
name = "CellSimulation"
version = "0.1.0"
edition = "2021"

[features]
graphics = []

[dependencies]
minifb = "0.27.0"
rand = "0.8.5"
rustc-hash = "2.1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
